# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTourRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('mode_of_travel', models.CharField(blank=True, max_length=64)),
                ('ticket_cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('airport_cab_cost_home', models.DecimalField(decimal_places=2, max_digits=11)),
                ('airport_cab_cost_dest', models.DecimalField(decimal_places=2, max_digits=11)),
                ('bills_image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('bills_image_caption', models.CharField(blank=True, max_length=160)),
                ('local_conveyance', models.CharField(blank=True, max_length=128)),
                ('draft', models.NullBooleanField(db_index=True, default=None)),
                ('is_submitted', models.NullBooleanField(db_index=True, default=None)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approving_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='employee_accounts.EmployeeAccount')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employee_accounts.EmployeeAccount')),
            ],
            options={
                'verbose_name': 'Employee Tour Request',
            },
        ),
    ]
