# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTourRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_by_manager', models.NullBooleanField(db_index=True, default=None)),
                ('manager_req_for_info', models.NullBooleanField(default=None)),
                ('approved_by_finance_manager', models.NullBooleanField(db_index=True, default=None)),
                ('finance_manager_req_for_info', models.NullBooleanField(default=None)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('emp_tour_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.EmployeeTourRequest')),
            ],
            options={
                'verbose_name': 'Employee Tour Request Status',
            },
        ),
    ]
