# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 16:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_employeetourrequeststatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetourrequeststatus',
            options={'verbose_name': 'Employee Tour Request Statu'},
        ),
    ]
