# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 16:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_accounts', '0001_initial'),
        ('tours', '0003_auto_20170316_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetourrequeststatus',
            name='approving_finance_manager',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='finance_manager', to='employee_accounts.EmployeeAccount'),
        ),
    ]
