# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20170317_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetourrequest',
            name='tour_name',
            field=models.CharField(blank=True, default='My Tour', max_length=64),
        ),
    ]
