# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0006_employeetourrequest_tour_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetourrequest',
            name='is_submitted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
