# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0007_auto_20170318_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetourrequest',
            name='is_approved',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
