# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_employeetourrequest_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetourrequest',
            name='hotel_cost',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
