# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0009_employeetourrequest_hotel_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetourrequest',
            name='hotel_cost',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=11),
        ),
    ]
