# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 08:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0010_auto_20170318_0748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetourrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='employeetourrequest',
            name='request_status',
            field=models.CharField(default='Pending', max_length=32),
        ),
    ]
