# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0013_auto_20170320_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetourrequeststatus',
            name='emp_tour_req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emp_request_status', to='tours.EmployeeTourRequest'),
        ),
    ]
