# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 07:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0014_auto_20170320_0612'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(default='Pending', max_length=32)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employeetourrequest',
            name='request_status',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, related_name='emp_req_status', to='tours.EmployeeRequestStatus'),
        ),
        migrations.AlterField(
            model_name='employeetourrequeststatus',
            name='approved_by_finance_manager',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Rejected', 'Reject'), ('Request For Information', 'Request For Information')], default='Pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='employeetourrequeststatus',
            name='approved_by_manager',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approve'), ('Rejected', 'Reject'), ('Request For Information', 'Request For Information')], default='Pending', max_length=32),
        ),
    ]
