# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0016_auto_20170320_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='employeetourrequest',
            name='request_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.EmployeeRequestStatus'),
        ),
    ]
