# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0019_auto_20170320_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetourrequest',
            name='request_status',
            field=models.ForeignKey(default='Pending', on_delete=django.db.models.deletion.CASCADE, to='tours.EmployeeRequestStatus'),
        ),
    ]
