# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0021_auto_20170320_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeetourrequest',
            name='hotel_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
    ]
