# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0023_auto_20170320_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetourrequeststatus',
            name='submitted_to_finance_manager',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
