# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0026_auto_20170322_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequeststatus',
            name='status_link',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
